// Generated by CIRCT unknown git version

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module ALUExeUnit_4(	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  input         clock,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  input         reset,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7]
  input         io_req_valid,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [6:0]  io_req_bits_uop_uopc,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_is_rvc,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [9:0]  io_req_bits_uop_fu_code,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [3:0]  io_req_bits_uop_ctrl_br_type,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [1:0]  io_req_bits_uop_ctrl_op1_sel,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [2:0]  io_req_bits_uop_ctrl_op2_sel,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [2:0]  io_req_bits_uop_ctrl_imm_sel,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [4:0]  io_req_bits_uop_ctrl_op_fcn,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_ctrl_fcn_dw,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_is_br,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_is_jalr,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_is_jal,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_is_sfb,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [19:0] io_req_bits_uop_br_mask,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [4:0]  io_req_bits_uop_br_tag,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [5:0]  io_req_bits_uop_ftq_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_edge_inst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [5:0]  io_req_bits_uop_pc_lob,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_taken,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [19:0] io_req_bits_uop_imm_packed,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [6:0]  io_req_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [4:0]  io_req_bits_uop_ldq_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [4:0]  io_req_bits_uop_stq_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [6:0]  io_req_bits_uop_pdst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [6:0]  io_req_bits_uop_prs1,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_bypassable,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_is_amo,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [1:0]  io_req_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [64:0] io_req_bits_rs1_data,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [64:0] io_req_bits_rs2_data,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input         io_req_bits_kill,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_iresp_valid,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [6:0]  io_iresp_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [6:0]  io_iresp_bits_uop_pdst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_iresp_bits_uop_bypassable,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_iresp_bits_uop_is_amo,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_iresp_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [1:0]  io_iresp_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [64:0] io_iresp_bits_data,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_bypass_0_valid,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [6:0]  io_bypass_0_bits_uop_pdst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [1:0]  io_bypass_0_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [64:0] io_bypass_0_bits_data,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_bypass_1_valid,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [6:0]  io_bypass_1_bits_uop_pdst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [1:0]  io_bypass_1_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [64:0] io_bypass_1_bits_data,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_bypass_2_valid,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [6:0]  io_bypass_2_bits_uop_pdst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [1:0]  io_bypass_2_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [64:0] io_bypass_2_bits_data,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [19:0] io_brupdate_b1_resolve_mask,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  input  [19:0] io_brupdate_b1_mispredict_mask,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_brinfo_uop_is_rvc,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [19:0] io_brinfo_uop_br_mask,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [4:0]  io_brinfo_uop_br_tag,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [5:0]  io_brinfo_uop_ftq_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_brinfo_uop_edge_inst,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [5:0]  io_brinfo_uop_pc_lob,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [6:0]  io_brinfo_uop_rob_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [4:0]  io_brinfo_uop_ldq_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [4:0]  io_brinfo_uop_stq_idx,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_brinfo_valid,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_brinfo_mispredict,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output        io_brinfo_taken,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [2:0]  io_brinfo_cfi_type,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [1:0]  io_brinfo_pc_sel,	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
  output [20:0] io_brinfo_target_offset	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14]
);

  wire        _PipelinedMulUnit_io_resp_valid;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:326:18]
  wire [6:0]  _PipelinedMulUnit_io_resp_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:326:18]
  wire [6:0]  _PipelinedMulUnit_io_resp_bits_uop_pdst;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:326:18]
  wire        _PipelinedMulUnit_io_resp_bits_uop_bypassable;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:326:18]
  wire        _PipelinedMulUnit_io_resp_bits_uop_is_amo;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:326:18]
  wire        _PipelinedMulUnit_io_resp_bits_uop_uses_stq;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:326:18]
  wire [1:0]  _PipelinedMulUnit_io_resp_bits_uop_dst_rtype;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:326:18]
  wire [63:0] _PipelinedMulUnit_io_resp_bits_data;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:326:18]
  wire        _ALUUnit_io_resp_valid;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:271:17]
  wire [6:0]  _ALUUnit_io_resp_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:271:17]
  wire [6:0]  _ALUUnit_io_resp_bits_uop_pdst;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:271:17]
  wire        _ALUUnit_io_resp_bits_uop_bypassable;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:271:17]
  wire        _ALUUnit_io_resp_bits_uop_is_amo;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:271:17]
  wire        _ALUUnit_io_resp_bits_uop_uses_stq;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:271:17]
  wire [1:0]  _ALUUnit_io_resp_bits_uop_dst_rtype;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:271:17]
  wire [63:0] _ALUUnit_io_resp_bits_data;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:271:17]
  wire [63:0] _ALUUnit_io_bypass_0_bits_data;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:271:17]
  wire [63:0] _ALUUnit_io_bypass_1_bits_data;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:271:17]
  wire [63:0] _ALUUnit_io_bypass_2_bits_data;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:271:17]
  `ifndef SYNTHESIS	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:425:10]
    wire [1:0] _GEN = {1'h0, _ALUUnit_io_resp_valid} + {1'h0, _PipelinedMulUnit_io_resp_valid};	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:271:17, :326:18, :425:20]
    always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:425:10]
      if (~reset & _GEN[1]) begin	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:425:{10,20,58}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:425:10]
          $error("Assertion failed: Multiple functional units are fighting over the write port.\n    at execution-unit.scala:425 assert ((PopCount(iresp_fu_units.map(_.io.resp.valid)) <= 1.U && !div_resp_val) ||\n");	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:425:10]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:425:10]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:425:10]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  ALUUnit_2 ALUUnit (	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:271:17]
    .clock                          (clock),
    .reset                          (reset),
    .io_req_valid                   (io_req_valid & (io_req_bits_uop_fu_code == 10'h1 | io_req_bits_uop_fu_code == 10'h2 | io_req_bits_uop_fu_code == 10'h20 & io_req_bits_uop_uopc != 7'h6C)),	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:275:20, :276:{32,43}, :277:{32,43}, :278:{32,43,67}]
    .io_req_bits_uop_uopc           (io_req_bits_uop_uopc),
    .io_req_bits_uop_is_rvc         (io_req_bits_uop_is_rvc),
    .io_req_bits_uop_ctrl_br_type   (io_req_bits_uop_ctrl_br_type),
    .io_req_bits_uop_ctrl_op1_sel   (io_req_bits_uop_ctrl_op1_sel),
    .io_req_bits_uop_ctrl_op2_sel   (io_req_bits_uop_ctrl_op2_sel),
    .io_req_bits_uop_ctrl_imm_sel   (io_req_bits_uop_ctrl_imm_sel),
    .io_req_bits_uop_ctrl_op_fcn    (io_req_bits_uop_ctrl_op_fcn),
    .io_req_bits_uop_ctrl_fcn_dw    (io_req_bits_uop_ctrl_fcn_dw),
    .io_req_bits_uop_is_br          (io_req_bits_uop_is_br),
    .io_req_bits_uop_is_jalr        (io_req_bits_uop_is_jalr),
    .io_req_bits_uop_is_jal         (io_req_bits_uop_is_jal),
    .io_req_bits_uop_is_sfb         (io_req_bits_uop_is_sfb),
    .io_req_bits_uop_br_mask        (io_req_bits_uop_br_mask),
    .io_req_bits_uop_br_tag         (io_req_bits_uop_br_tag),
    .io_req_bits_uop_ftq_idx        (io_req_bits_uop_ftq_idx),
    .io_req_bits_uop_edge_inst      (io_req_bits_uop_edge_inst),
    .io_req_bits_uop_pc_lob         (io_req_bits_uop_pc_lob),
    .io_req_bits_uop_taken          (io_req_bits_uop_taken),
    .io_req_bits_uop_imm_packed     (io_req_bits_uop_imm_packed),
    .io_req_bits_uop_rob_idx        (io_req_bits_uop_rob_idx),
    .io_req_bits_uop_ldq_idx        (io_req_bits_uop_ldq_idx),
    .io_req_bits_uop_stq_idx        (io_req_bits_uop_stq_idx),
    .io_req_bits_uop_pdst           (io_req_bits_uop_pdst),
    .io_req_bits_uop_prs1           (io_req_bits_uop_prs1),
    .io_req_bits_uop_bypassable     (io_req_bits_uop_bypassable),
    .io_req_bits_uop_is_amo         (io_req_bits_uop_is_amo),
    .io_req_bits_uop_uses_stq       (io_req_bits_uop_uses_stq),
    .io_req_bits_uop_dst_rtype      (io_req_bits_uop_dst_rtype),
    .io_req_bits_rs1_data           (io_req_bits_rs1_data[63:0]),	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:283:30]
    .io_req_bits_rs2_data           (io_req_bits_rs2_data[63:0]),	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:284:30]
    .io_req_bits_kill               (io_req_bits_kill),
    .io_resp_valid                  (_ALUUnit_io_resp_valid),
    .io_resp_bits_uop_rob_idx       (_ALUUnit_io_resp_bits_uop_rob_idx),
    .io_resp_bits_uop_pdst          (_ALUUnit_io_resp_bits_uop_pdst),
    .io_resp_bits_uop_bypassable    (_ALUUnit_io_resp_bits_uop_bypassable),
    .io_resp_bits_uop_is_amo        (_ALUUnit_io_resp_bits_uop_is_amo),
    .io_resp_bits_uop_uses_stq      (_ALUUnit_io_resp_bits_uop_uses_stq),
    .io_resp_bits_uop_dst_rtype     (_ALUUnit_io_resp_bits_uop_dst_rtype),
    .io_resp_bits_data              (_ALUUnit_io_resp_bits_data),
    .io_brupdate_b1_resolve_mask    (io_brupdate_b1_resolve_mask),
    .io_brupdate_b1_mispredict_mask (io_brupdate_b1_mispredict_mask),
    .io_bypass_0_valid              (io_bypass_0_valid),
    .io_bypass_0_bits_uop_pdst      (io_bypass_0_bits_uop_pdst),
    .io_bypass_0_bits_uop_dst_rtype (io_bypass_0_bits_uop_dst_rtype),
    .io_bypass_0_bits_data          (_ALUUnit_io_bypass_0_bits_data),
    .io_bypass_1_valid              (io_bypass_1_valid),
    .io_bypass_1_bits_uop_pdst      (io_bypass_1_bits_uop_pdst),
    .io_bypass_1_bits_uop_dst_rtype (io_bypass_1_bits_uop_dst_rtype),
    .io_bypass_1_bits_data          (_ALUUnit_io_bypass_1_bits_data),
    .io_bypass_2_valid              (io_bypass_2_valid),
    .io_bypass_2_bits_uop_pdst      (io_bypass_2_bits_uop_pdst),
    .io_bypass_2_bits_uop_dst_rtype (io_bypass_2_bits_uop_dst_rtype),
    .io_bypass_2_bits_data          (_ALUUnit_io_bypass_2_bits_data),
    .io_brinfo_uop_is_rvc           (io_brinfo_uop_is_rvc),
    .io_brinfo_uop_br_mask          (io_brinfo_uop_br_mask),
    .io_brinfo_uop_br_tag           (io_brinfo_uop_br_tag),
    .io_brinfo_uop_ftq_idx          (io_brinfo_uop_ftq_idx),
    .io_brinfo_uop_edge_inst        (io_brinfo_uop_edge_inst),
    .io_brinfo_uop_pc_lob           (io_brinfo_uop_pc_lob),
    .io_brinfo_uop_rob_idx          (io_brinfo_uop_rob_idx),
    .io_brinfo_uop_ldq_idx          (io_brinfo_uop_ldq_idx),
    .io_brinfo_uop_stq_idx          (io_brinfo_uop_stq_idx),
    .io_brinfo_valid                (io_brinfo_valid),
    .io_brinfo_mispredict           (io_brinfo_mispredict),
    .io_brinfo_taken                (io_brinfo_taken),
    .io_brinfo_cfi_type             (io_brinfo_cfi_type),
    .io_brinfo_pc_sel               (io_brinfo_pc_sel),
    .io_brinfo_target_offset        (io_brinfo_target_offset)
  );	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:271:17]
  PipelinedMulUnit PipelinedMulUnit (	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:326:18]
    .clock                          (clock),
    .reset                          (reset),
    .io_req_valid                   (io_req_valid & io_req_bits_uop_fu_code[3]),	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:104:14, :328:47]
    .io_req_bits_uop_ctrl_op_fcn    (io_req_bits_uop_ctrl_op_fcn),
    .io_req_bits_uop_ctrl_fcn_dw    (io_req_bits_uop_ctrl_fcn_dw),
    .io_req_bits_uop_br_mask        (io_req_bits_uop_br_mask),
    .io_req_bits_uop_rob_idx        (io_req_bits_uop_rob_idx),
    .io_req_bits_uop_pdst           (io_req_bits_uop_pdst),
    .io_req_bits_uop_bypassable     (io_req_bits_uop_bypassable),
    .io_req_bits_uop_is_amo         (io_req_bits_uop_is_amo),
    .io_req_bits_uop_uses_stq       (io_req_bits_uop_uses_stq),
    .io_req_bits_uop_dst_rtype      (io_req_bits_uop_dst_rtype),
    .io_req_bits_rs1_data           (io_req_bits_rs1_data[63:0]),	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:283:30]
    .io_req_bits_rs2_data           (io_req_bits_rs2_data[63:0]),	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:284:30]
    .io_req_bits_kill               (io_req_bits_kill),
    .io_resp_valid                  (_PipelinedMulUnit_io_resp_valid),
    .io_resp_bits_uop_rob_idx       (_PipelinedMulUnit_io_resp_bits_uop_rob_idx),
    .io_resp_bits_uop_pdst          (_PipelinedMulUnit_io_resp_bits_uop_pdst),
    .io_resp_bits_uop_bypassable    (_PipelinedMulUnit_io_resp_bits_uop_bypassable),
    .io_resp_bits_uop_is_amo        (_PipelinedMulUnit_io_resp_bits_uop_is_amo),
    .io_resp_bits_uop_uses_stq      (_PipelinedMulUnit_io_resp_bits_uop_uses_stq),
    .io_resp_bits_uop_dst_rtype     (_PipelinedMulUnit_io_resp_bits_uop_dst_rtype),
    .io_resp_bits_data              (_PipelinedMulUnit_io_resp_bits_data),
    .io_brupdate_b1_resolve_mask    (io_brupdate_b1_resolve_mask),
    .io_brupdate_b1_mispredict_mask (io_brupdate_b1_mispredict_mask)
  );	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:326:18]
  assign io_iresp_valid = _ALUUnit_io_resp_valid | _PipelinedMulUnit_io_resp_valid;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7, :271:17, :326:18, :409:71]
  assign io_iresp_bits_uop_rob_idx = _ALUUnit_io_resp_valid ? _ALUUnit_io_resp_bits_uop_rob_idx : _PipelinedMulUnit_io_resp_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7, :271:17, :326:18, src/main/scala/chisel3/util/Mux.scala:50:70]
  assign io_iresp_bits_uop_pdst = _ALUUnit_io_resp_valid ? _ALUUnit_io_resp_bits_uop_pdst : _PipelinedMulUnit_io_resp_bits_uop_pdst;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7, :271:17, :326:18, src/main/scala/chisel3/util/Mux.scala:50:70]
  assign io_iresp_bits_uop_bypassable = _ALUUnit_io_resp_valid ? _ALUUnit_io_resp_bits_uop_bypassable : _PipelinedMulUnit_io_resp_bits_uop_bypassable;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7, :271:17, :326:18, src/main/scala/chisel3/util/Mux.scala:50:70]
  assign io_iresp_bits_uop_is_amo = _ALUUnit_io_resp_valid ? _ALUUnit_io_resp_bits_uop_is_amo : _PipelinedMulUnit_io_resp_bits_uop_is_amo;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7, :271:17, :326:18, src/main/scala/chisel3/util/Mux.scala:50:70]
  assign io_iresp_bits_uop_uses_stq = _ALUUnit_io_resp_valid ? _ALUUnit_io_resp_bits_uop_uses_stq : _PipelinedMulUnit_io_resp_bits_uop_uses_stq;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7, :271:17, :326:18, src/main/scala/chisel3/util/Mux.scala:50:70]
  assign io_iresp_bits_uop_dst_rtype = _ALUUnit_io_resp_valid ? _ALUUnit_io_resp_bits_uop_dst_rtype : _PipelinedMulUnit_io_resp_bits_uop_dst_rtype;	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7, :271:17, :326:18, src/main/scala/chisel3/util/Mux.scala:50:70]
  assign io_iresp_bits_data = {1'h0, _ALUUnit_io_resp_valid ? _ALUUnit_io_resp_bits_data : _PipelinedMulUnit_io_resp_bits_data};	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7, :271:17, :326:18, :412:24, src/main/scala/chisel3/util/Mux.scala:50:70]
  assign io_bypass_0_bits_data = {1'h0, _ALUUnit_io_bypass_0_bits_data};	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7, :271:17, :293:15]
  assign io_bypass_1_bits_data = {1'h0, _ALUUnit_io_bypass_1_bits_data};	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7, :271:17, :293:15]
  assign io_bypass_2_bits_data = {1'h0, _ALUUnit_io_bypass_2_bits_data};	// @[generators/boom/src/main/scala/v3/exu/execution-units/execution-unit.scala:204:7, :271:17, :293:15]
endmodule

