// Generated by CIRCT unknown git version

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module BoomDuplicatedDataArray(	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
  input          clock,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
  input          io_read_0_valid,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  input  [7:0]   io_read_0_bits_way_en,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  input  [11:0]  io_read_0_bits_addr,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  input          io_read_1_valid,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  input  [7:0]   io_read_1_bits_way_en,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  input  [11:0]  io_read_1_bits_addr,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  input          io_write_valid,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  input  [7:0]   io_write_bits_way_en,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  input  [11:0]  io_write_bits_addr,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  input  [1:0]   io_write_bits_wmask,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  input  [127:0] io_write_bits_data,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  output [127:0] io_resp_0_0,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  output [127:0] io_resp_0_1,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  output [127:0] io_resp_0_2,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  output [127:0] io_resp_0_3,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  output [127:0] io_resp_0_4,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  output [127:0] io_resp_0_5,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  output [127:0] io_resp_0_6,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  output [127:0] io_resp_0_7,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  output [127:0] io_resp_1_0,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  output [127:0] io_resp_1_1,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  output [127:0] io_resp_1_2,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  output [127:0] io_resp_1_3,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  output [127:0] io_resp_1_4,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  output [127:0] io_resp_1_5,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  output [127:0] io_resp_1_6,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
  output [127:0] io_resp_1_7	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:270:14]
);

  wire [127:0] _array_7_1_R0_data;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [127:0] _array_6_1_R0_data;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [127:0] _array_5_1_R0_data;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [127:0] _array_4_1_R0_data;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [127:0] _array_3_1_R0_data;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [127:0] _array_2_1_R0_data;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [127:0] _array_1_1_R0_data;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [127:0] _array_0_1_R0_data;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [127:0] _array_7_0_R0_data;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [127:0] _array_6_0_R0_data;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [127:0] _array_5_0_R0_data;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [127:0] _array_4_0_R0_data;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [127:0] _array_3_0_R0_data;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [127:0] _array_2_0_R0_data;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [127:0] _array_1_0_R0_data;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [127:0] _array_0_0_R0_data;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire         array_0_0_MPORT_en = io_write_bits_way_en[0] & io_write_valid;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:{33,37}]
  reg  [127:0] io_resp_0_0_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31]
  wire         array_1_1_MPORT_9_en = io_write_bits_way_en[1] & io_write_valid;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:{33,37}]
  reg  [127:0] io_resp_0_1_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31]
  wire         array_2_0_MPORT_2_en = io_write_bits_way_en[2] & io_write_valid;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:{33,37}]
  reg  [127:0] io_resp_0_2_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31]
  wire         array_3_0_MPORT_3_en = io_write_bits_way_en[3] & io_write_valid;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:{33,37}]
  reg  [127:0] io_resp_0_3_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31]
  wire         array_4_0_MPORT_4_en = io_write_bits_way_en[4] & io_write_valid;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:{33,37}]
  reg  [127:0] io_resp_0_4_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31]
  wire         array_5_0_MPORT_5_en = io_write_bits_way_en[5] & io_write_valid;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:{33,37}]
  reg  [127:0] io_resp_0_5_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31]
  wire         array_6_0_MPORT_6_en = io_write_bits_way_en[6] & io_write_valid;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:{33,37}]
  reg  [127:0] io_resp_0_6_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31]
  wire         array_7_0_MPORT_7_en = io_write_bits_way_en[7] & io_write_valid;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:{33,37}]
  reg  [127:0] io_resp_0_7_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31]
  reg  [127:0] io_resp_1_0_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31]
  reg  [127:0] io_resp_1_1_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31]
  reg  [127:0] io_resp_1_2_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31]
  reg  [127:0] io_resp_1_3_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31]
  reg  [127:0] io_resp_1_4_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31]
  reg  [127:0] io_resp_1_5_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31]
  reg  [127:0] io_resp_1_6_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31]
  reg  [127:0] io_resp_1_7_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31]
  always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
    io_resp_0_0_REG <= _array_0_0_R0_data;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    io_resp_0_1_REG <= _array_1_0_R0_data;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    io_resp_0_2_REG <= _array_2_0_R0_data;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    io_resp_0_3_REG <= _array_3_0_R0_data;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    io_resp_0_4_REG <= _array_4_0_R0_data;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    io_resp_0_5_REG <= _array_5_0_R0_data;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    io_resp_0_6_REG <= _array_6_0_R0_data;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    io_resp_0_7_REG <= _array_7_0_R0_data;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    io_resp_1_0_REG <= _array_0_1_R0_data;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    io_resp_1_1_REG <= _array_1_1_R0_data;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    io_resp_1_2_REG <= _array_2_1_R0_data;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    io_resp_1_3_REG <= _array_3_1_R0_data;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    io_resp_1_4_REG <= _array_4_1_R0_data;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    io_resp_1_5_REG <= _array_5_1_R0_data;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    io_resp_1_6_REG <= _array_6_1_R0_data;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    io_resp_1_7_REG <= _array_7_1_R0_data;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:31, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:63];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
    initial begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
        `INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
        for (logic [6:0] i = 7'h0; i < 7'h40; i += 7'h1) begin
          _RANDOM[i[5:0]] = `RANDOM;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
        end	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
        io_resp_0_0_REG = {_RANDOM[6'h0], _RANDOM[6'h1], _RANDOM[6'h2], _RANDOM[6'h3]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
        io_resp_0_1_REG = {_RANDOM[6'h4], _RANDOM[6'h5], _RANDOM[6'h6], _RANDOM[6'h7]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
        io_resp_0_2_REG = {_RANDOM[6'h8], _RANDOM[6'h9], _RANDOM[6'hA], _RANDOM[6'hB]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
        io_resp_0_3_REG = {_RANDOM[6'hC], _RANDOM[6'hD], _RANDOM[6'hE], _RANDOM[6'hF]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
        io_resp_0_4_REG = {_RANDOM[6'h10], _RANDOM[6'h11], _RANDOM[6'h12], _RANDOM[6'h13]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
        io_resp_0_5_REG = {_RANDOM[6'h14], _RANDOM[6'h15], _RANDOM[6'h16], _RANDOM[6'h17]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
        io_resp_0_6_REG = {_RANDOM[6'h18], _RANDOM[6'h19], _RANDOM[6'h1A], _RANDOM[6'h1B]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
        io_resp_0_7_REG = {_RANDOM[6'h1C], _RANDOM[6'h1D], _RANDOM[6'h1E], _RANDOM[6'h1F]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
        io_resp_1_0_REG = {_RANDOM[6'h20], _RANDOM[6'h21], _RANDOM[6'h22], _RANDOM[6'h23]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
        io_resp_1_1_REG = {_RANDOM[6'h24], _RANDOM[6'h25], _RANDOM[6'h26], _RANDOM[6'h27]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
        io_resp_1_2_REG = {_RANDOM[6'h28], _RANDOM[6'h29], _RANDOM[6'h2A], _RANDOM[6'h2B]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
        io_resp_1_3_REG = {_RANDOM[6'h2C], _RANDOM[6'h2D], _RANDOM[6'h2E], _RANDOM[6'h2F]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
        io_resp_1_4_REG = {_RANDOM[6'h30], _RANDOM[6'h31], _RANDOM[6'h32], _RANDOM[6'h33]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
        io_resp_1_5_REG = {_RANDOM[6'h34], _RANDOM[6'h35], _RANDOM[6'h36], _RANDOM[6'h37]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
        io_resp_1_6_REG = {_RANDOM[6'h38], _RANDOM[6'h39], _RANDOM[6'h3A], _RANDOM[6'h3B]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
        io_resp_1_7_REG = {_RANDOM[6'h3C], _RANDOM[6'h3D], _RANDOM[6'h3E], _RANDOM[6'h3F]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  array_0_0 array_0_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_0_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:287:38]
    .R0_en   (io_read_0_bits_way_en[0] & io_read_0_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .R0_data (_array_0_0_R0_data),
    .W0_addr (io_write_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:284:34]
    .W0_en   (array_0_0_MPORT_en),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:37]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  array_1_0 array_1_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_0_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:287:38]
    .R0_en   (io_read_0_bits_way_en[1] & io_read_0_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .R0_data (_array_1_0_R0_data),
    .W0_addr (io_write_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:284:34]
    .W0_en   (array_1_1_MPORT_9_en),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:37]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  array_2_0 array_2_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_0_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:287:38]
    .R0_en   (io_read_0_bits_way_en[2] & io_read_0_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .R0_data (_array_2_0_R0_data),
    .W0_addr (io_write_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:284:34]
    .W0_en   (array_2_0_MPORT_2_en),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:37]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  array_3_0 array_3_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_0_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:287:38]
    .R0_en   (io_read_0_bits_way_en[3] & io_read_0_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .R0_data (_array_3_0_R0_data),
    .W0_addr (io_write_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:284:34]
    .W0_en   (array_3_0_MPORT_3_en),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:37]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  array_4_0 array_4_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_0_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:287:38]
    .R0_en   (io_read_0_bits_way_en[4] & io_read_0_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .R0_data (_array_4_0_R0_data),
    .W0_addr (io_write_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:284:34]
    .W0_en   (array_4_0_MPORT_4_en),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:37]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  array_5_0 array_5_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_0_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:287:38]
    .R0_en   (io_read_0_bits_way_en[5] & io_read_0_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .R0_data (_array_5_0_R0_data),
    .W0_addr (io_write_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:284:34]
    .W0_en   (array_5_0_MPORT_5_en),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:37]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  array_6_0 array_6_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_0_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:287:38]
    .R0_en   (io_read_0_bits_way_en[6] & io_read_0_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .R0_data (_array_6_0_R0_data),
    .W0_addr (io_write_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:284:34]
    .W0_en   (array_6_0_MPORT_6_en),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:37]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  array_7_0 array_7_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_0_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:287:38]
    .R0_en   (io_read_0_bits_way_en[7] & io_read_0_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .R0_data (_array_7_0_R0_data),
    .W0_addr (io_write_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:284:34]
    .W0_en   (array_7_0_MPORT_7_en),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:37]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  array_0_1 array_0_1 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_1_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:287:38]
    .R0_en   (io_read_1_bits_way_en[0] & io_read_1_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .R0_data (_array_0_1_R0_data),
    .W0_addr (io_write_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:284:34]
    .W0_en   (array_0_0_MPORT_en),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:37]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  array_1_1 array_1_1 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_1_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:287:38]
    .R0_en   (io_read_1_bits_way_en[1] & io_read_1_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .R0_data (_array_1_1_R0_data),
    .W0_addr (io_write_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:284:34]
    .W0_en   (array_1_1_MPORT_9_en),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:37]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  array_2_1 array_2_1 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_1_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:287:38]
    .R0_en   (io_read_1_bits_way_en[2] & io_read_1_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .R0_data (_array_2_1_R0_data),
    .W0_addr (io_write_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:284:34]
    .W0_en   (array_2_0_MPORT_2_en),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:37]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  array_3_1 array_3_1 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_1_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:287:38]
    .R0_en   (io_read_1_bits_way_en[3] & io_read_1_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .R0_data (_array_3_1_R0_data),
    .W0_addr (io_write_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:284:34]
    .W0_en   (array_3_0_MPORT_3_en),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:37]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  array_4_1 array_4_1 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_1_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:287:38]
    .R0_en   (io_read_1_bits_way_en[4] & io_read_1_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .R0_data (_array_4_1_R0_data),
    .W0_addr (io_write_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:284:34]
    .W0_en   (array_4_0_MPORT_4_en),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:37]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  array_5_1 array_5_1 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_1_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:287:38]
    .R0_en   (io_read_1_bits_way_en[5] & io_read_1_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .R0_data (_array_5_1_R0_data),
    .W0_addr (io_write_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:284:34]
    .W0_en   (array_5_0_MPORT_5_en),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:37]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  array_6_1 array_6_1 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_1_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:287:38]
    .R0_en   (io_read_1_bits_way_en[6] & io_read_1_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .R0_data (_array_6_1_R0_data),
    .W0_addr (io_write_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:284:34]
    .W0_en   (array_6_0_MPORT_6_en),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:37]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  array_7_1 array_7_1 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .R0_addr (io_read_1_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:287:38]
    .R0_en   (io_read_1_bits_way_en[7] & io_read_1_valid),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .R0_data (_array_7_1_R0_data),
    .W0_addr (io_write_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:284:34]
    .W0_en   (array_7_0_MPORT_7_en),	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:295:37]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  assign io_resp_0_0 = io_resp_0_0_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
  assign io_resp_0_1 = io_resp_0_1_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
  assign io_resp_0_2 = io_resp_0_2_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
  assign io_resp_0_3 = io_resp_0_3_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
  assign io_resp_0_4 = io_resp_0_4_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
  assign io_resp_0_5 = io_resp_0_5_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
  assign io_resp_0_6 = io_resp_0_6_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
  assign io_resp_0_7 = io_resp_0_7_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
  assign io_resp_1_0 = io_resp_1_0_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
  assign io_resp_1_1 = io_resp_1_1_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
  assign io_resp_1_2 = io_resp_1_2_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
  assign io_resp_1_3 = io_resp_1_3_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
  assign io_resp_1_4 = io_resp_1_4_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
  assign io_resp_1_5 = io_resp_1_5_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
  assign io_resp_1_6 = io_resp_1_6_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
  assign io_resp_1_7 = io_resp_1_7_REG;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:281:7, :299:31]
endmodule

