// Generated by CIRCT unknown git version
// VCS coverage exclude_file
module regfile_128x64(	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
  input  [6:0]  R0_addr,
  input         R0_en,
  input         R0_clk,
  output [63:0] R0_data,
  input  [6:0]  R1_addr,
  input         R1_en,
  input         R1_clk,
  output [63:0] R1_data,
  input  [6:0]  R2_addr,
  input         R2_en,
  input         R2_clk,
  output [63:0] R2_data,
  input  [6:0]  R3_addr,
  input         R3_en,
  input         R3_clk,
  output [63:0] R3_data,
  input  [6:0]  R4_addr,
  input         R4_en,
  input         R4_clk,
  output [63:0] R4_data,
  input  [6:0]  R5_addr,
  input         R5_en,
  input         R5_clk,
  output [63:0] R5_data,
  input  [6:0]  R6_addr,
  input         R6_en,
  input         R6_clk,
  output [63:0] R6_data,
  input  [6:0]  R7_addr,
  input         R7_en,
  input         R7_clk,
  output [63:0] R7_data,
  input  [6:0]  R8_addr,
  input         R8_en,
  input         R8_clk,
  output [63:0] R8_data,
  input  [6:0]  R9_addr,
  input         R9_en,
  input         R9_clk,
  output [63:0] R9_data,
  input  [6:0]  R10_addr,
  input         R10_en,
  input         R10_clk,
  output [63:0] R10_data,
  input  [6:0]  R11_addr,
  input         R11_en,
  input         R11_clk,
  output [63:0] R11_data,
  input  [6:0]  W0_addr,
  input         W0_en,
  input         W0_clk,
  input  [63:0] W0_data,
  input  [6:0]  W1_addr,
  input         W1_en,
  input         W1_clk,
  input  [63:0] W1_data,
  input  [6:0]  W2_addr,
  input         W2_en,
  input         W2_clk,
  input  [63:0] W2_data,
  input  [6:0]  W3_addr,
  input         W3_en,
  input         W3_clk,
  input  [63:0] W3_data,
  input  [6:0]  W4_addr,
  input         W4_en,
  input         W4_clk,
  input  [63:0] W4_data,
  input  [6:0]  W5_addr,
  input         W5_en,
  input         W5_clk,
  input  [63:0] W5_data
);

  reg [63:0] Memory[0:127];	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
  always @(posedge W0_clk) begin	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
    if (W0_en & 1'h1)	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
      Memory[W0_addr] <= W0_data;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
    if (W1_en & 1'h1)	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
      Memory[W1_addr] <= W1_data;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
    if (W2_en & 1'h1)	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
      Memory[W2_addr] <= W2_data;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
    if (W3_en & 1'h1)	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
      Memory[W3_addr] <= W3_data;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
    if (W4_en & 1'h1)	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
      Memory[W4_addr] <= W4_data;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
    if (W5_en & 1'h1)	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
      Memory[W5_addr] <= W5_data;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
    reg [63:0] _RANDOM_MEM;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
    initial begin	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
      `INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
      `ifdef RANDOMIZE_MEM_INIT	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
        for (logic [7:0] i = 8'h0; i < 8'h80; i += 8'h1) begin
          for (logic [6:0] j = 7'h0; j < 7'h40; j += 7'h20) begin
            _RANDOM_MEM[j +: 32] = `RANDOM;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
          end
          Memory[i[6:0]] = _RANDOM_MEM;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
        end
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 64'bx;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
  assign R1_data = R1_en ? Memory[R1_addr] : 64'bx;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
  assign R2_data = R2_en ? Memory[R2_addr] : 64'bx;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
  assign R3_data = R3_en ? Memory[R3_addr] : 64'bx;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
  assign R4_data = R4_en ? Memory[R4_addr] : 64'bx;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
  assign R5_data = R5_en ? Memory[R5_addr] : 64'bx;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
  assign R6_data = R6_en ? Memory[R6_addr] : 64'bx;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
  assign R7_data = R7_en ? Memory[R7_addr] : 64'bx;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
  assign R8_data = R8_en ? Memory[R8_addr] : 64'bx;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
  assign R9_data = R9_en ? Memory[R9_addr] : 64'bx;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
  assign R10_data = R10_en ? Memory[R10_addr] : 64'bx;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
  assign R11_data = R11_en ? Memory[R11_addr] : 64'bx;	// @[generators/boom/src/main/scala/v3/exu/register-read/regfile.scala:117:20]
endmodule

