// Generated by CIRCT unknown git version

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module RenameBusyTable_1(	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7]
  input        clock,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7]
  input        reset,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7]
  input  [6:0] io_ren_uops_0_pdst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input  [6:0] io_ren_uops_0_prs1,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input  [6:0] io_ren_uops_0_prs2,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input  [6:0] io_ren_uops_0_prs3,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input  [6:0] io_ren_uops_1_pdst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input  [6:0] io_ren_uops_1_prs1,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input  [6:0] io_ren_uops_1_prs2,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input  [6:0] io_ren_uops_1_prs3,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input  [6:0] io_ren_uops_2_pdst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input  [6:0] io_ren_uops_2_prs1,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input  [6:0] io_ren_uops_2_prs2,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input  [6:0] io_ren_uops_2_prs3,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input  [6:0] io_ren_uops_3_pdst,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input  [6:0] io_ren_uops_3_prs1,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input  [6:0] io_ren_uops_3_prs2,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input  [6:0] io_ren_uops_3_prs3,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  output       io_busy_resps_0_prs1_busy,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  output       io_busy_resps_0_prs2_busy,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  output       io_busy_resps_0_prs3_busy,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  output       io_busy_resps_1_prs1_busy,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  output       io_busy_resps_1_prs2_busy,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  output       io_busy_resps_1_prs3_busy,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  output       io_busy_resps_2_prs1_busy,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  output       io_busy_resps_2_prs2_busy,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  output       io_busy_resps_2_prs3_busy,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  output       io_busy_resps_3_prs1_busy,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  output       io_busy_resps_3_prs2_busy,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  output       io_busy_resps_3_prs3_busy,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input        io_rebusy_reqs_0,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input        io_rebusy_reqs_1,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input        io_rebusy_reqs_2,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input        io_rebusy_reqs_3,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input  [6:0] io_wb_pdsts_0,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input  [6:0] io_wb_pdsts_1,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input  [6:0] io_wb_pdsts_2,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input  [6:0] io_wb_pdsts_3,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input        io_wb_valids_0,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input        io_wb_valids_1,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input        io_wb_valids_2,	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
  input        io_wb_valids_3	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:37:14]
);

  reg  [127:0] busy_table;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:48:27]
  wire [127:0] _io_busy_resps_0_prs1_busy_T = busy_table >> io_ren_uops_0_prs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:48:27, :67:45]
  wire [127:0] _io_busy_resps_0_prs2_busy_T = busy_table >> io_ren_uops_0_prs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:48:27, :68:45]
  wire [127:0] _io_busy_resps_0_prs3_busy_T = busy_table >> io_ren_uops_0_prs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:48:27, :69:45]
  wire [127:0] _io_busy_resps_1_prs1_busy_T = busy_table >> io_ren_uops_1_prs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:48:27, :67:45]
  wire [127:0] _io_busy_resps_1_prs2_busy_T = busy_table >> io_ren_uops_1_prs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:48:27, :68:45]
  wire [127:0] _io_busy_resps_1_prs3_busy_T = busy_table >> io_ren_uops_1_prs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:48:27, :69:45]
  wire [127:0] _io_busy_resps_2_prs1_busy_T = busy_table >> io_ren_uops_2_prs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:48:27, :67:45]
  wire [127:0] _io_busy_resps_2_prs2_busy_T = busy_table >> io_ren_uops_2_prs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:48:27, :68:45]
  wire [127:0] _io_busy_resps_2_prs3_busy_T = busy_table >> io_ren_uops_2_prs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:48:27, :69:45]
  wire [127:0] _io_busy_resps_3_prs1_busy_T = busy_table >> io_ren_uops_3_prs1;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:48:27, :67:45]
  wire [127:0] _io_busy_resps_3_prs2_busy_T = busy_table >> io_ren_uops_3_prs2;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:48:27, :68:45]
  wire [127:0] _io_busy_resps_3_prs3_busy_T = busy_table >> io_ren_uops_3_prs3;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:48:27, :69:45]
  always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7]
    if (reset)	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7]
      busy_table <= 128'h0;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:48:27]
    else	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7]
      busy_table <= busy_table & ~(128'h1 << io_wb_pdsts_0 & {128{io_wb_valids_0}} | 128'h1 << io_wb_pdsts_1 & {128{io_wb_valids_1}} | 128'h1 << io_wb_pdsts_2 & {128{io_wb_valids_2}} | 128'h1 << io_wb_pdsts_3 & {128{io_wb_valids_3}}) | 128'h1 << io_ren_uops_0_pdst & {128{io_rebusy_reqs_0}} | 128'h1 << io_ren_uops_1_pdst & {128{io_rebusy_reqs_1}} | 128'h1 << io_ren_uops_2_pdst & {128{io_rebusy_reqs_2}} | 128'h1 << io_ren_uops_3_pdst & {128{io_rebusy_reqs_3}};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:48:27, :50:{34,36}, :51:{48,54,88}, :53:39, :54:{49,55,87}, src/main/scala/chisel3/util/OneHot.scala:58:35]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:3];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7]
    initial begin	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7]
        `INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7]
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7]
        end	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7]
        busy_table = {_RANDOM[2'h0], _RANDOM[2'h1], _RANDOM[2'h2], _RANDOM[2'h3]};	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7, :48:27]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_busy_resps_0_prs1_busy = _io_busy_resps_0_prs1_busy_T[0];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7, :67:45]
  assign io_busy_resps_0_prs2_busy = _io_busy_resps_0_prs2_busy_T[0];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7, :68:45]
  assign io_busy_resps_0_prs3_busy = _io_busy_resps_0_prs3_busy_T[0];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7, :69:45]
  assign io_busy_resps_1_prs1_busy = _io_busy_resps_1_prs1_busy_T[0];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7, :67:45]
  assign io_busy_resps_1_prs2_busy = _io_busy_resps_1_prs2_busy_T[0];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7, :68:45]
  assign io_busy_resps_1_prs3_busy = _io_busy_resps_1_prs3_busy_T[0];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7, :69:45]
  assign io_busy_resps_2_prs1_busy = _io_busy_resps_2_prs1_busy_T[0];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7, :67:45]
  assign io_busy_resps_2_prs2_busy = _io_busy_resps_2_prs2_busy_T[0];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7, :68:45]
  assign io_busy_resps_2_prs3_busy = _io_busy_resps_2_prs3_busy_T[0];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7, :69:45]
  assign io_busy_resps_3_prs1_busy = _io_busy_resps_3_prs1_busy_T[0];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7, :67:45]
  assign io_busy_resps_3_prs2_busy = _io_busy_resps_3_prs2_busy_T[0];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7, :68:45]
  assign io_busy_resps_3_prs3_busy = _io_busy_resps_3_prs3_busy_T[0];	// @[generators/boom/src/main/scala/v3/exu/rename/rename-busytable.scala:27:7, :69:45]
endmodule

