// Generated by CIRCT unknown git version
module rob_debug_inst_mem(	// @[generators/boom/src/main/scala/v3/exu/rob.scala:296:41]
  input [4:0]   R0_addr,
  input         R0_en,
  input         R0_clk,
  input [4:0]   W0_addr,
  input         W0_clk,
  input [127:0] W0_data,
  input [3:0]   W0_mask
);

  rob_debug_inst_mem_ext rob_debug_inst_mem_ext (	// @[generators/boom/src/main/scala/v3/exu/rob.scala:296:41]
    .R0_addr (R0_addr),
    .R0_en   (R0_en),
    .R0_clk  (R0_clk),
    .R0_data (/* unused */),
    .W0_addr (W0_addr),
    .W0_en   (1'h1),	// @[generators/boom/src/main/scala/v3/exu/rob.scala:296:41]
    .W0_clk  (W0_clk),
    .W0_data (W0_data),
    .W0_mask (W0_mask)
  );	// @[generators/boom/src/main/scala/v3/exu/rob.scala:296:41]
endmodule

