// Generated by CIRCT unknown git version
module Arbiter1_Bool(	// @[src/main/scala/chisel3/util/Arbiter.scala:133:7]
  output io_in_0_ready,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input  io_out_ready	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
);

  assign io_in_0_ready = io_out_ready;	// @[src/main/scala/chisel3/util/Arbiter.scala:133:7]
endmodule

