// Generated by CIRCT unknown git version

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module NLPrefetcher(	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7]
  input         clock,	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7]
  input         reset,	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7]
  input         io_mshr_avail,	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:26:14]
  input         io_req_val,	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:26:14]
  input  [39:0] io_req_addr,	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:26:14]
  input  [1:0]  io_req_coh_state,	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:26:14]
  input         io_prefetch_ready,	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:26:14]
  output        io_prefetch_valid,	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:26:14]
  output [4:0]  io_prefetch_bits_uop_mem_cmd,	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:26:14]
  output [39:0] io_prefetch_bits_addr	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:26:14]
);

  reg         req_valid;	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:50:26]
  reg  [39:0] req_addr;	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:51:22]
  reg  [4:0]  req_cmd;	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:52:22]
  wire        io_prefetch_valid_0 = req_valid & io_mshr_avail;	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:50:26, :64:45]
  wire [39:0] _mshr_req_addr_T = io_req_addr + 40'h40;	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:54:35]
  wire        _GEN = io_req_val & ({_mshr_req_addr_T[39:28], _mshr_req_addr_T[27:16] ^ 12'h800} == 24'h0 | {_mshr_req_addr_T[39:32], _mshr_req_addr_T[31:28] ^ 4'h8} == 12'h0);	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:54:35, :56:20, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{31,41,46,59}, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:685:42]
  always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7]
    if (reset)	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7]
      req_valid <= 1'h0;	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7, :50:26]
    else	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7]
      req_valid <= _GEN | ~(io_prefetch_ready & io_prefetch_valid_0) & req_valid;	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:50:26, :56:{20,34}, :57:15, :60:34, :61:15, :64:45, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    if (_GEN) begin	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:56:20]
      req_addr <= _mshr_req_addr_T;	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:51:22, :54:35]
      req_cmd <= {4'h1, io_req_coh_state[1]};	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:52:22, :59:15, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:20:53]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7]
    initial begin	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7]
        `INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7]
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7]
        end	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7]
        req_valid = _RANDOM[1'h0][0];	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7, :50:26]
        req_addr = {_RANDOM[1'h0][31:1], _RANDOM[1'h1][8:0]};	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7, :50:26, :51:22]
        req_cmd = _RANDOM[1'h1][13:9];	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7, :51:22, :52:22]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_prefetch_valid = io_prefetch_valid_0;	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7, :64:45]
  assign io_prefetch_bits_uop_mem_cmd = req_cmd;	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7, :52:22]
  assign io_prefetch_bits_addr = req_addr;	// @[generators/boom/src/main/scala/v3/lsu/prefetcher.scala:48:7, :51:22]
endmodule

