// Generated by CIRCT unknown git version

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Queue1_BranchPredictionBundle(	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
  input          clock,	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
  input          reset,	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
  output         io_enq_ready,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [39:0]  io_enq_bits_pc,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_0_taken,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_0_is_br,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_0_is_jal,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_0_predicted_pc_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [39:0]  io_enq_bits_preds_0_predicted_pc_bits,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_1_taken,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_1_is_br,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_1_is_jal,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_1_predicted_pc_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [39:0]  io_enq_bits_preds_1_predicted_pc_bits,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_2_taken,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_2_is_br,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_2_is_jal,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_2_predicted_pc_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [39:0]  io_enq_bits_preds_2_predicted_pc_bits,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_3_taken,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_3_is_br,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_3_is_jal,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_3_predicted_pc_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [39:0]  io_enq_bits_preds_3_predicted_pc_bits,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_4_taken,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_4_is_br,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_4_is_jal,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_4_predicted_pc_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [39:0]  io_enq_bits_preds_4_predicted_pc_bits,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_5_taken,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_5_is_br,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_5_is_jal,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_5_predicted_pc_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [39:0]  io_enq_bits_preds_5_predicted_pc_bits,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_6_taken,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_6_is_br,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_6_is_jal,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_6_predicted_pc_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [39:0]  io_enq_bits_preds_6_predicted_pc_bits,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_7_taken,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_7_is_br,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_7_is_jal,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_preds_7_predicted_pc_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [39:0]  io_enq_bits_preds_7_predicted_pc_bits,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [119:0] io_enq_bits_meta_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [119:0] io_enq_bits_meta_1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_deq_ready,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [39:0]  io_deq_bits_pc,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_preds_0_taken,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_preds_0_predicted_pc_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [39:0]  io_deq_bits_preds_0_predicted_pc_bits,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_preds_1_taken,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_preds_1_predicted_pc_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [39:0]  io_deq_bits_preds_1_predicted_pc_bits,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_preds_2_taken,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_preds_2_predicted_pc_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [39:0]  io_deq_bits_preds_2_predicted_pc_bits,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_preds_3_taken,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_preds_3_predicted_pc_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [39:0]  io_deq_bits_preds_3_predicted_pc_bits,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_preds_4_taken,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_preds_4_predicted_pc_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [39:0]  io_deq_bits_preds_4_predicted_pc_bits,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_preds_5_taken,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_preds_5_predicted_pc_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [39:0]  io_deq_bits_preds_5_predicted_pc_bits,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_preds_6_taken,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_preds_6_predicted_pc_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [39:0]  io_deq_bits_preds_6_predicted_pc_bits,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_preds_7_taken,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_preds_7_predicted_pc_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [39:0]  io_deq_bits_preds_7_predicted_pc_bits,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [119:0] io_deq_bits_meta_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [119:0] io_deq_bits_meta_1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_lhist_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_lhist_1	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
);

  wire         io_enq_ready_0;	// @[src/main/scala/chisel3/util/Decoupled.scala:286:16, :306:{24,39}]
  reg  [633:0] ram;	// @[src/main/scala/chisel3/util/Decoupled.scala:256:91]
  reg          full;	// @[src/main/scala/chisel3/util/Decoupled.scala:259:27]
  wire         do_enq = ~(~full & io_deq_ready) & io_enq_ready_0 & io_enq_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :261:28, :263:27, :286:16, :298:17, :301:{26,35}, :306:{24,39}]
  assign io_enq_ready_0 = io_deq_ready | ~full;	// @[src/main/scala/chisel3/util/Decoupled.scala:259:27, :286:{16,19}, :306:{24,39}]
  always @(posedge clock) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    if (do_enq)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, :263:27, :298:17, :301:{26,35}]
      ram <= {2'h0, io_enq_bits_meta_1, io_enq_bits_meta_0, io_enq_bits_preds_7_predicted_pc_bits, io_enq_bits_preds_7_predicted_pc_valid, io_enq_bits_preds_7_is_jal, io_enq_bits_preds_7_is_br, io_enq_bits_preds_7_taken, io_enq_bits_preds_6_predicted_pc_bits, io_enq_bits_preds_6_predicted_pc_valid, io_enq_bits_preds_6_is_jal, io_enq_bits_preds_6_is_br, io_enq_bits_preds_6_taken, io_enq_bits_preds_5_predicted_pc_bits, io_enq_bits_preds_5_predicted_pc_valid, io_enq_bits_preds_5_is_jal, io_enq_bits_preds_5_is_br, io_enq_bits_preds_5_taken, io_enq_bits_preds_4_predicted_pc_bits, io_enq_bits_preds_4_predicted_pc_valid, io_enq_bits_preds_4_is_jal, io_enq_bits_preds_4_is_br, io_enq_bits_preds_4_taken, io_enq_bits_preds_3_predicted_pc_bits, io_enq_bits_preds_3_predicted_pc_valid, io_enq_bits_preds_3_is_jal, io_enq_bits_preds_3_is_br, io_enq_bits_preds_3_taken, io_enq_bits_preds_2_predicted_pc_bits, io_enq_bits_preds_2_predicted_pc_valid, io_enq_bits_preds_2_is_jal, io_enq_bits_preds_2_is_br, io_enq_bits_preds_2_taken, io_enq_bits_preds_1_predicted_pc_bits, io_enq_bits_preds_1_predicted_pc_valid, io_enq_bits_preds_1_is_jal, io_enq_bits_preds_1_is_br, io_enq_bits_preds_1_taken, io_enq_bits_preds_0_predicted_pc_bits, io_enq_bits_preds_0_predicted_pc_valid, io_enq_bits_preds_0_is_jal, io_enq_bits_preds_0_is_br, io_enq_bits_preds_0_taken, io_enq_bits_pc};	// @[src/main/scala/chisel3/util/Decoupled.scala:256:91]
    if (reset)	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      full <= 1'h0;	// @[src/main/scala/chisel3/util/Decoupled.scala:259:27]
    else if (~(do_enq == (full & io_deq_ready & (io_enq_valid | full))))	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :263:27, :264:27, :276:{15,27}, :277:16, :285:16, :297:{24,39}, :298:17, :300:14, :301:{26,35}]
      full <= do_enq;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :263:27, :298:17, :301:{26,35}]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:19];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    initial begin	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
        for (logic [4:0] i = 5'h0; i < 5'h14; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
        end	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
        ram = {_RANDOM[5'h0][31:1], _RANDOM[5'h1], _RANDOM[5'h2], _RANDOM[5'h3], _RANDOM[5'h4], _RANDOM[5'h5], _RANDOM[5'h6], _RANDOM[5'h7], _RANDOM[5'h8], _RANDOM[5'h9], _RANDOM[5'hA], _RANDOM[5'hB], _RANDOM[5'hC], _RANDOM[5'hD], _RANDOM[5'hE], _RANDOM[5'hF], _RANDOM[5'h10], _RANDOM[5'h11], _RANDOM[5'h12], _RANDOM[5'h13][26:0]};	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
        full = _RANDOM[5'h0][0];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_enq_ready = io_enq_ready_0;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :286:16, :306:{24,39}]
  assign io_deq_bits_pc = full ? ram[39:0] : io_enq_bits_pc;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_0_taken = full ? ram[40] : io_enq_bits_preds_0_taken;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_0_predicted_pc_valid = full ? ram[43] : io_enq_bits_preds_0_predicted_pc_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_0_predicted_pc_bits = full ? ram[83:44] : io_enq_bits_preds_0_predicted_pc_bits;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_1_taken = full ? ram[84] : io_enq_bits_preds_1_taken;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_1_predicted_pc_valid = full ? ram[87] : io_enq_bits_preds_1_predicted_pc_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_1_predicted_pc_bits = full ? ram[127:88] : io_enq_bits_preds_1_predicted_pc_bits;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_2_taken = full ? ram[128] : io_enq_bits_preds_2_taken;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_2_predicted_pc_valid = full ? ram[131] : io_enq_bits_preds_2_predicted_pc_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_2_predicted_pc_bits = full ? ram[171:132] : io_enq_bits_preds_2_predicted_pc_bits;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_3_taken = full ? ram[172] : io_enq_bits_preds_3_taken;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_3_predicted_pc_valid = full ? ram[175] : io_enq_bits_preds_3_predicted_pc_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_3_predicted_pc_bits = full ? ram[215:176] : io_enq_bits_preds_3_predicted_pc_bits;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_4_taken = full ? ram[216] : io_enq_bits_preds_4_taken;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_4_predicted_pc_valid = full ? ram[219] : io_enq_bits_preds_4_predicted_pc_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_4_predicted_pc_bits = full ? ram[259:220] : io_enq_bits_preds_4_predicted_pc_bits;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_5_taken = full ? ram[260] : io_enq_bits_preds_5_taken;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_5_predicted_pc_valid = full ? ram[263] : io_enq_bits_preds_5_predicted_pc_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_5_predicted_pc_bits = full ? ram[303:264] : io_enq_bits_preds_5_predicted_pc_bits;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_6_taken = full ? ram[304] : io_enq_bits_preds_6_taken;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_6_predicted_pc_valid = full ? ram[307] : io_enq_bits_preds_6_predicted_pc_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_6_predicted_pc_bits = full ? ram[347:308] : io_enq_bits_preds_6_predicted_pc_bits;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_7_taken = full ? ram[348] : io_enq_bits_preds_7_taken;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_7_predicted_pc_valid = full ? ram[351] : io_enq_bits_preds_7_predicted_pc_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_preds_7_predicted_pc_bits = full ? ram[391:352] : io_enq_bits_preds_7_predicted_pc_bits;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_meta_0 = full ? ram[511:392] : io_enq_bits_meta_0;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_meta_1 = full ? ram[631:512] : io_enq_bits_meta_1;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_lhist_0 = full & ram[632];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
  assign io_deq_bits_lhist_1 = full & ram[633];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91, :259:27, :293:17, :298:17, :299:19]
endmodule

